### ISSUE TITLE
wiring diagrams not fetching

### ISSUE THREAD

**Issue by bmcdonough** [iamtheyammer/fetch-ford-service-manuals#14]
```
...
Downloading manual page Transmission Support Crossmember - 10-Speed Automatic Transmission – 10R80 as HTML, PDF (docID: G1928889)
Saved workshop manual!
Saving wiring manual...
/root/fetch-ford-service-manuals/src/index.ts:99
  await wiringContext.addCookies(transformedCookieString);
                      ^
browserContext.addCookies: Protocol error (Storage.setCookies): Invalid cookie fields
    at run (/root/fetch-ford-service-manuals/src/index.ts:99:23) {
  name: 'Error'
}
```

snippet of the cookie
-----
Key=Value;

snippet of params.json
-----
  "wiring": {
    "environment": "prod_1_3_XXXXXXX",
    "bookType": "svg"

**Comment by bmcdonough** [comment]
I realize now, I needed the complete cookie, which includes the domain and expiration.
-----
`Key=Value; Domain=.subDomain.Domain.com; Path=/; Expires=DayOfWeek, DayOfMonth Month Year HH:MM:SS GMT; Max-Age=1234; Secure
`

**Comment by iamtheyammer** [comment]
Yup. Apologies for the delay getting to it. Reply to re-open this issue if you need any more help.
