### ISSUE TITLE
Trouble Getting Information For params.json

### ISSUE THREAD

**Issue by limitedAtonement** [iamtheyammer/fetch-ford-service-manuals#15]
I followed the instructions to select my vehicle from PTS, but it looks like my vehicle isn't there

> Do not use your VIN.
> On the left, choose By Year & Model, then select your car's year and model.
> Press GO once selected.

When I use my VIN, I see a request in the network tab for `https://www.fordtechservice.dealerconnection.com/publication/Book/workshop/6290/1FBZA2CB7JKG62917?model=Transit%20-%20TH%20(V363%20NA)&modelyear=2018` (VIN adjusted for anonymity). That suggests I'm looking for model "Transit - TH (V363 NA)", however, the page only lists the following models:

![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/7562490/8934eab5-890a-4ac6-ba2f-b0950065b116)

I'll be looking for an alternative way to interact with the manuals, but if you know another way to get the information for `params.json`, that would be great!

**Comment by limitedAtonement** [comment]
By the way, this page's error seems like it could be useful... https://www.fordservicecontent.com/Ford_Content/PublicationRuntimeRefreshPTS//wiring/TableofContent?environment=prod_1_3_4162024&bookType=svg&book=EJW&contentlanguage=EN&contentmarket=US&fromPageBase=https:B%2F%2Fwww.fordtechservice.dealerconnection.com

I get 

![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/7562490/0b705a07-4c29-4ade-9800-89247f7bfe40)

**Comment by limitedAtonement** [comment]
I was able to gather the information here and there to get the PDF manuals, but the wiring diagram part didn't work. I was able to put together a shell script with cURL to get the wiring diagrams which wound up being much better because I got the SVGs without converting to PNG, so the size is much smaller and quality much greater. Let me know if you want to see that shell script.

**Comment by iamtheyammer** [comment]
Hey, thanks for opening an issue. I've never seen this before! You could try doing all the data collection steps again without clearing the network pane, then using the search box to search for the keys. Perhaps it's a different request?

Normally I'd say you could email your PTS login to me but I'm away from my laptop for the week. Glad you got the workshop manual at least!

**Comment by byron-behm** [comment]
> I was able to gather the information here and there to get the PDF manuals, but the wiring diagram part didn't work. I was able to put together a shell script with cURL to get the wiring diagrams which wound up being much better because I got the SVGs without converting to PNG, so the size is much smaller and quality much greater. Let me know if you want to see that shell script.

I would love to see the shell script. I am getting the same error when I try to download the wiring diagrams. My workshop manual was able to download without any issues.

**Comment by limitedAtonement** [comment]
Here you go dude. I got values for `dealer_connect_cookies` and `ford_cookies` from my browser. You'll also need to fill in `get_page_url` and `get_page_list_url` URLs from your browser (or get the values from `templates/params.json`).

The script should be readable...if (when) something goes wrong, just read the code and try to make sense of it (don't be intimidated ;-) unless you really don't know how HTTP works, then maybe this won't work for you).

I got the `toc.json` file from the first couple steps of this repo's script.

My script is idempotent to a degree: if you've already downloaded a file, it won't download it again. If you want to start over for some reason, delete the directories starting with numbers.

Good luck out there!

```
#!/bin/bash
set -x;

dealer_connect_cookies='cookie: dtCookie=v_4_srv_26_sn_1; Ford.TSO.PTSSuite=ekiuLg; TPS%2DPERM=CBB5751E; PERSISTENT=market=US&; PREFERENCES=lan; TPS%2DMEMBERSHIP=authby=WSL; rxVisitor=17132859563; dtSa=-; ASP.NET_SessionId=jj   etc';
ford_cookies='cookie: CONTENT_AUTH=permissions=~WSJX|~; CONTENT_PERMISSIONS=permiss...';
ford_parameters=(-H 'accept: */*' -H 'accept-language: en-US,en;q=0.9' -H "$ford_cookies" -H 'origin: https://www.fordtechservice.dealerconnection.com' -H 'referer: https://www.fordtechservice.dealerconnection.com/' \
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36');
dealer_connect_parameters=(-H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' -H "$dealer_connect_cookies"
    -H 'accept-language: en-US,en;q=0.9'
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
	-H 'referer: https://www.fordtechservice.dealerconnection.com/wiring/page/?book=EJW&vehicleId=6000&vin=&cell=003%20%20&page=5%20%20&item=0&country=&bookType=svg&language=&languageCode=ENUSA&sortBy=&title=Introduction');

get_page_url(){
    cell=$1;
    # change to base 10 (strip leading 0s)
    page=$((10#$2));
    printf 'https://www.fordtechservice.dealerconnection.com/wiring/page/?book=EJW&vehicleId=6000&vin=&cell=%s&page=%s&item=0&country=&bookType=svg&language=&languageCode=ENUSA&sortBy=&title=Introduction' "$cell%20%20" "$page%20%20";
}

get_page_list_url(){
    cell=$1;
    printf 'https://www.fordservicecontent.com/Ford_Content/PublicationRuntimeRefreshPTS//wiring/PageList?environment=prod_1_3_4000024&book=EJW&bookType=svg&contentmarket=&contentlanguage=&cell=%s+&page=1++&languageCode=ENUSA' "$cell";
}

if [[ ! -e toc.json ]]; then
    echo "No toc.json file!" >&2;
    exit 1;
fi;

toc_length=$(jq length toc.json);

for (( toc_item = 0 ; toc_item < toc_length ; toc_item++ )); do
    echo "Starting loop..." >&2;
    type=$(jq -r ".[${toc_item}].Type" < toc.json) || exit;
    if [[ "$type" != "Page" ]]; then
        continue;
    fi;
    number=$(jq -r ".[${toc_item}].Number" < toc.json) || exit;
    title=$(jq -r ".[${toc_item}].Title" < toc.json) || exit;
    directory="$number - $title";
    # Replace all slashes to dashes so that they're not interpreted as directories
    directory=${directory//\//-};
    if [[ ! -d "$directory" ]]; then
        mkdir "$directory" || exit;
    fi;
    cd "$directory" || exit;
    if [[ ! -e pagelist.json ]]; then
        curl "$(get_page_list_url "$number")" "${ford_parameters[@]}" -o pagelist.json || exit;
    else
        echo "Already have pagelist for $PWD";
    fi;
    pages=$(jq length pagelist.json) || exit;
    for (( page = 0 ; page < pages ; page++ )); do
        real_page=$(jq -r ".[${page}]" < pagelist.json) || exit;
        if [[ ! -e "$real_page".html ]]; then
            curl "$(get_page_url "$number" "$real_page")" "${dealer_connect_parameters[@]}" -o "$real_page.html" || exit
        else
            echo "Already have page $real_page.html";
        fi;
		svg_url=$(\grep -oP "url: '\Khttps[^']+" < "$real_page.html") || exit;
		svg_file=${svg_url##*/};
		if [[ ! -e "$svg_file" ]]; then
			curl "$svg_url" "${ford_parameters[@]}" -o "$svg_file" || exit;
            echo "sleeping before downloading more...";
            sleep .5;
        fi;
    done;
    cd ..;
done;
```

**Comment by limitedAtonement** [comment]
If you get all this working, your next question will be: How do I view these SVG files!?

# Web Browser

Opening in Chromium (or firefox) should show the images, but it just shows the SVG source. To get it to show the pictures for real, change the first line from

```svg
<svg xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-0.5 -0.5 1100 850" height="100%" width="100%" id="svgDoc">
```
to
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-0.5 -0.5 1100 850" height="100%" width="100%" id="svgDoc">
```
(add the `xmlns` attribute to tell the browser that it's really a SVG file??) Writing a script to inject this into all the SVG files shouldn't be too bad.

# Inkscape

Inkscape shows the images just fine. Inkscape comes with `inkview` which also shows the files, but it's not zoomable and pannable which is a serious drawback in these images.

## Convert to PNG

`inkscape.exe -o compass.png -w 1440 compass.svg;`

# Convert to PNG

## `ffmpeg`
Use ffmpeg to convert the images `ffmpeg -i 1.svg 1.png`, but this will yield a very small image. I'm not sure how to change the resolution/dimensions but it should be easy as pie.

## ImageMagick

`convert 1.svg 1.png`. That's an old invocation style, but the output looks good. If you want to adjust the output, manual is here: https://www.imagemagick.org/Usage/basics/#convert

# Python Script

It looks like cairo provides a svg2png converter: https://superuser.com/a/1321947/52865

**Comment by iamtheyammer** [comment]
Back to my laptop-- amazing work @limitedAtonement! I'll take a look at what's making your shell script different than the JavaScript and try to implement those changes.

**Comment by iamtheyammer** [comment]
Once I get the fetching figured out, I can do the SVG-PNG conversion, along with the first-line replacement, all inside of the script.

**Comment by iamtheyammer** [comment]
Also, @byron-behm, do you have a PTS login I can use to test the script? If so, I'd love to borrow it! My email is on my GitHub profile.

**Comment by iamtheyammer** [comment]
Ok, I've tracked down the two core issues at play here. The first issue (that was causing the 500) is a missing query parameter. That was a pretty easy fix. The second is how I was putting the cookies into the emulated browser: I was using an invalid combination of cookie attributes causing the browser to reject the cookies, which then led to it being unauthenticated (see issue [here](https://github.com/microsoft/playwright/issues/306660)).

I should have a fix for both of these issues in less than a week or so.

**Comment by iamtheyammer** [comment]
Fix for this issue is in the experimental-wiring branch, which will merge soon.
