### ISSUE TITLE
How to use toc.json

### ISSUE THREAD

**Issue by navy2x** [iamtheyammer/fetch-ford-service-manuals#16]
What is the intended way to use the toc.json file? The readme states: 

`The toc.json file contains the computer-readable table of contents, with the name mapped to the "document number", which is used to fetch the PDF.`

My toc.json looks like this:
![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/59400832/356ca27b-3221-404c-be64-b23af5ea3151)

I would like to use this file to create one big pdf of all the other pdfs merged, but I'd like to have the toc preserved as bookmarks. Is this possible?

By the way, this is great, thanks for making the script. I found it with a google search before trying to make my own.

**Comment by iamtheyammer** [comment]
There isn't really an intended way to use this file. It's used when fetching documents, and I used it a bunch when debugging the large recursive download algorithm.

I think the best way to get an interactive ToC is to programmatically modify the `cover.html` file to link to all the other files on disk (using relative URLs, like how the pre-2003 ToCs work). This is something I can add but I'm not sure how long it'll take.

As for making one combined PDF, you'll probably need to find some other program that can do that and add bookmarks. If you did a DFS through `toc.json` you'd get the right order to stitch the files, then you could add some kind of "pdf bookmark" at the top of each stitched document, and link that back to the `cover.html` anchor tags. Not terribly easy but it'd be an awesome contribution to this project!
