### ISSUE TITLE
page.pdf: Protocol error (Page.printToPDF): Printing failed

### ISSUE THREAD

**Issue by kitteh5** [iamtheyammer/fetch-ford-service-manuals#4]
Hello, sorry if this is a bit disjointed. I haven't touched a single line of code in four years, so I'm relearning everything as I go here.

I am using Ubuntu 22.04 LTS in WSL2 to run your fetch program. I believe I've gotten everything installed correctly regarding dependencies, but I still keep running into one stupid error. I have run out of skill at this point. 

The manual I am trying to download is for a 2009 Fusion.

The error in question is "protocol error, printing failed".

Attached is a screenshot of my terminal, maybe you could piece something together that I am not.

Thanks!

![Screenshot 2022-12-22 212706](https://user-images.githubusercontent.com/34580260/209258756-67debb1e-19fa-4f07-8c47-d42320d71c33.png)

**Comment by iamtheyammer** [comment]
Hm, printing failed. Based on your other issue, I'd imagine this is also a Chrome related bug. I'd try `yarn up playwright` to update playwright and its browsers, then run it again.
