### ISSUE TITLE
page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by kitteh5** [iamtheyammer/fetch-ford-service-manuals#5]
Hello, I just got this error when trying to run the program again, this time it failed differently. 

The error this time is a page crashing inside the headless Chromium instance? This error references the Master DTC List, which did successfully download. I can open the HTML document just fine, I am presuming this is before the PDF conversion step (see previous issue raised, where it was page.pdf that failed to print). 

I am downloading a manual for a 2009 Fusion, using Ubuntu 22.04 in WSL2. I will attach a screenshot of my terminal and maybe you can see something that I am missing here. 

Thanks!

![Screenshot 2022-12-22 214536](https://user-images.githubusercontent.com/34580260/209260652-ae8849e6-a0bf-4d36-93c3-8f1ade4893b0.png)

**Comment by iamtheyammer** [comment]
Hm, that's an odd one. You're correct that it failed during the PDF conversion. I doubt you're missing something-- this is likely a Chrome bug. The best way to debug this would be to disable headless mode inside the code and watch the page and see what happens, but I doubt you have a PTS subscription anymore and neither do I :(
