### ISSUE TITLE
[Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by thewatsonator3** [iamtheyammer/fetch-ford-service-manuals#6]
I get this error when running:

PS C:\F150\fetch-ford-service-manuals> yarn start -c templates/params.json -s templates/cookieString.txt -o \F150\Manual
Creating a headless chromium instance...
Downloading and processing table of contents...
Saving manual files...
Downloading manual page Master DTC Chart (All-Inclusive).html (docID: S9132masterdtcindex)
Downloading manual page Specifications.html (docID: S9132specindex)
Downloading manual PDF Metrics https://www.fordservicecontent.com/Ford_Content//pdf/workshop/METRICS_EN.pdf
Skipping relative path /publication/TorqueWrenchFormulas?lang=ENUSA for name Torque Wrench Adapter Formulas
Downloading manual page Alphabetical Index.html (docID: S9132alphaindex)
Downloading manual page ADT Test Page.html (docID: adttestindex)
Downloading manual page SPA Test Page.html (docID: S9132spaindex_test)
Downloading manual page About this Manual.html (docID: G2164606)
[Error: ENOENT: no such file or directory, open 'C:\F150\Manual\1: General Information\00: Service Information\100-00 General Information\Description and Operation\About this Manual.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\F150\\Manual\\1: General Information\\00: Service Information\\100-00 General Information\\Description and Operation\\About this Manual.html'
}

**Comment by thewatsonator3** [comment]
I tried every which way thinking maybe my installs were bad.. Not sure if the webpage has changed since the implementation of this program and that's why it errors out...

**Comment by thewatsonator3** [comment]
I can confirm the file isn't there. That's what is so weird. While doing
the download it jumps to trying to open a file. It also has a colon in it
where folder is 1: General ---etc. however you can't have colons in folder
names so it threw me off.

Let me try to get the trace error. I am on windows 11.

LEt

**Comment by iamtheyammer** [comment]
Huh, that could very well be the issue— I'll be honest, I've only tested this on POSIX systems and on Windows via WSL— and yeah, colons aren't allowed in paths on windows ( https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions ). The other pages that downloaded— are they not in a folder with a colon?

If that's the issue, I'd probably just check and see if we're on Windows and implement something that removes colons and other reserved characters.

**Comment by thewatsonator3** [comment]
Correct, the other pages that downloaded are not in a folder with a colon. They look like this:
![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/55631088/273ea79d-1ff8-48ba-8554-7266fedd9b67)
![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/55631088/034c9cc6-5bc4-49fe-84ca-11d38d7411b5)

**Comment by eyeball29** [comment]
Did this get resolved with any type of fix? I am having the same exact issue

**Comment by iamtheyammer** [comment]
Finally have some time to devote to this project. That’s my fix for tomorrow :)

**Comment by eyeball29** [comment]
Perfect timing for me! Just bought a 72 hours license today... Though I have a 2018 MKZ, so it might match the 2020 one pretty closely. 
I tried to run it in a VM box with Ubuntu and had some other issues probably related to dynamic storage so I'll see if I can troubleshoot there but if you can do a fix for the special characters on Windows it will be greatly appreciated!

**Comment by iamtheyammer** [comment]
Should be fixed now— on Windows, colons (and other illegal characters) are now removed before writing files/folders to disk.
