### ISSUE TITLE
Thank you soo much for your time & efforts

### ISSUE THREAD

**Issue by kkkumar-1** [iamtheyammer/fetch-ford-service-manuals#8]
Thank you soo much for your time & efforts.

Am able to pull the workshop manuals for my car.

The procedure worked beautifully.

Few observations.

1)  '.yarn' folder is missing, hence I have to manually create the folder and add the content.

**Comment by iamtheyammer** [comment]
Hi there, yes, you'll have to use yarn to install the dependencies. When you clone the repo and run `yarn`, it will use the yarn lockfile and package.json to create it.
